### ISSUE TITLE
contrib feature (or hotfix) delete: "Property 'delete' of object #<Object> is not a function"

### ISSUE THREAD

**Issue by jrw95** [brightcove-archive/zencoder_contribflow#2]
I created a new feature branch using contrib, called 

I was able to create both feature and hotfix branches using contrib.
I wanted to test deleting them, and got this error for both feature and hotfix delete attempts:

jwhisenant-retina:video-js jwhisenant$ contrib feature delete

/usr/local/lib/node_modules/contribflow/bin/contrib.js:8
contribflow[type][command](value1, value2);
                          ^
TypeError: Property 'delete' of object #<Object> is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/contribflow/bin/contrib.js:8:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)

**Comment by jrw95** [comment]
Closing. Tested that deletes work for both hotfixes and features.
