### ISSUE TITLE
contrib feature (or hotfix) submit: "prompt: undefined", followed by an error

### ISSUE THREAD

**Issue by jrw95** [brightcove-archive/zencoder_contribflow#4]
STR:
1. Create a new feature or hotfix branch with contrib.
2. In the branch you've created, run

``` bash
contrib feature submit
```

Expected:
You are prompted for your user name and password, and your feature is submitted as expected

Actual:
You get "prompt: undefined"
When you try to either enter your credentials, or press enter to leave the submit process, you get an error:

``` bash
jwhisenant-retina:video-js jwhisenant$ contrib feature submit
-----> Updating the feature/test1 branch
$ git checkout feature/test1 && git pull
Already up-to-date.
prompt: undefined: BCJwhisenant

/usr/local/lib/node_modules/contribflow/node_modules/github/index.js:397
            throw new Error("Basic authentication requires both a username and
                  ^
Error: Basic authentication requires both a username and password to be set
    at authenticate (/usr/local/lib/node_modules/contribflow/node_modules/github/index.js:397:19)
    at module.exports.pr.createFromBranch (/usr/local/lib/node_modules/contribflow/lib/pullrequest.js:81:14)
    at prompt.get (/usr/local/lib/node_modules/contribflow/node_modules/prompt/lib/prompt.js:179:34)
    at async.forEachSeries.iterate (/usr/local/lib/node_modules/contribflow/node_modules/prompt/node_modules/async/lib/async.js:116:25)
    at prompt.get (/usr/local/lib/node_modules/contribflow/node_modules/prompt/lib/prompt.js:174:7)
    at prompt.getInput (/usr/local/lib/node_modules/contribflow/node_modules/prompt/lib/prompt.js:232:14)
    at ReadStream.data (/usr/local/lib/node_modules/contribflow/node_modules/prompt/lib/prompt.js:365:7)
    at ReadStream.EventEmitter.emit (events.js:96:17)
    at TTY.onread (net.js:392:31)
```

**Comment by heff** [comment]
I think I've got all these fixed? Version 0.3.2 on npm

**Comment by jrw95** [comment]
Feature submit is working as expected.
I'll close this when I've had a chance to test 'contrib hotfix submit'

**Comment by jrw95** [comment]
Submitting for features and hotfixes works as expected.
Closing.
